### ISSUE TITLE
Crash udt:9001(41) when register  app to simulator

### ISSUE THREAD

**Issue by dhruvappstack** [DJI-Mobile-SDK-Tutorials/DJIBridgeAppDemo#1]
Please also provide if there is any permission issue of local area firewall
![screen shot 2 38 25 pm](https://cloud.githubusercontent.com/assets/13067085/20592695/fdc5c596-b254-11e6-9ae3-11ec1bba18bf.png)

**Comment by oliverou** [comment]
Hi @EonKid, thanks for your feedbacks. Could you provide us the process to reproduce this crash issue? 

Also, please provide the following info for us to help investigate the issue:

-  DJI iOS SDK version you are using (Like iOS SDK 3.4, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  iOS system version you are using (Like iOS 8.3, iOS 9, etc)
-  iOS device type you are using (Like iPhone5s, iPhone 6, iPad Air Wifi,  iPad mini 3 LTE, etc)
-  Xcode version you are using (Like Xcode 7.0)

Thanks!

**Comment by dhruvappstack** [comment]
@oliverou 
-DJI SDK version 3.4
-DJI Phantom 3 Advance
-iOS 10
- iPad Air
-Xcode 8.0
